### ISSUE TITLE
UI doesn't look good when drak theme for VS is being used

### ISSUE THREAD

**Issue by vladislav-naydenov** [ernstc/SolutionSecretsExtension#1]
When Visual Studio's theme is set to dark the Solution Secrets UI is too bright and unreadable.
![solution_secrets_when_dark_mode_on](https://user-images.githubusercontent.com/3259558/175811207-194234f5-4614-4f97-be2a-982c63130c90.png)

**Comment by ernstc** [comment]
Thanks @vladislav-naydenov this issue has been resolved with the 1.1.3 release.
